### ISSUE TITLE
current implementation status

### ISSUE THREAD

**Issue by DanielRuf** [jodator/ckeditor5-schema-structured-data#1]
Hi, I am currently researching different solutions for schema.org metadata and I'm curious about the current implementation status and progress of this addon.

What does work so far and what is not yet implemented?

Or is this addon not production ready yet?

**Comment by jodator** [comment]
@DanielRuf - it was proof-of-concept plugin rather something meant to be a production ready.

The code of the plugin might be really outdated since there were at least two betas and a final release since the time I worked on this plugin.

AFAIR the editing part was somewhat working but I have not the time to implement the UI for this feature.

Also the editing part lacks checking structured data metadata correctness (at least keywords as checking structure would be a bigger task).

At the moment I do not plan to work on this plugin but I might provide some updated code if there will be a bigger demand for this :)

**Comment by DanielRuf** [comment]
Hi @jodator, thanks for the information about the current status which is very helpful for me.

Might be interesting to support this. I'll let you know if I plan to invest some time to help with the further development and maintenance.
